Fix sentinel errors for builds against musl libc
This change fixes failing builds on systems with musl libc, where one
can experience lots of errors similar to following one:

```
FAILED: src/libnrtype/CMakeFiles/nrtype_LIB.dir/font-lister.cpp.o
/usr/bin/c++ ... -c ../src/libnrtype/font-lister.cpp
../src/libnrtype/font-lister.cpp: In function ‘void font_lister_cell_data_func2(GtkCellLayout*, GtkCellRenderer*, GtkTreeModel*, GtkTreeIter*, gpointer)’:
../src/libnrtype/font-lister.cpp:1236:64: error: missing sentinel in function call [-Werror=format=]
 1236 |     g_object_set(G_OBJECT(cell), "markup", markup.c_str(), NULL);
      |                                                                ^
```

Those errors are triggered by the compiler, because musl does not use
GCC's or Clang's __null extension for NULL definition, because it seems
non-conforming to the standard's requirements [1]. However, it is
possible to trigger this error with -Wstrict-null-sentinel GCC flag on
systems with glibc.

The change was originally made by dl2m, I applied the patch to the
version 1.0 release commit and rebased it on top of master branch.

[1]: https://git.musl-libc.org/cgit/musl/commit/?id=c8a9c22173f485c8c053709e1dfa0a617cb6be1a

Issue: https://gitlab.com/inkscape/inkscape/-/issues/1880
Based-on: https://gitlab.com/inkscape/inkscape/uploads/428412117341eb9601cb8ee01f2aae4b/0001-Fix-sentinal-errors.patch

(cherry picked from commit 19627310d9b5e85b7651946e8f48ceffa1cf07ee plus
fixes from commits 72a0d5585d4fd592e398c943f4dd290ff621c7f5 and
af51cf9da816603a2090e9a334c3f969b7a17e70)