On my Debian 10, the build was failing with:
/home/fsanches/devel/gitlab_fsanches/inkscape/src/object/sp-use-reference.h:45:50:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘SPCurve’
  static_assert(sizeof(_Tp)>0,

(cherry picked from commit ef99ede96aefc666ffff0f2b4a7663e52215cc28)